# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{authbuttons-rails}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dave Hulihan", "Hulihan Applications"]
  s.date = %q{2011-09-15}
  s.description = %q{A collection of authentication provider icons for Rails 3.1/Sprockets}
  s.email = %q{dave@hulihanapplications.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/authbuttons-rails.rb",
    "lib/authbuttons/rails.rb",
    "test/helper.rb",
    "test/test_authbuttons-rails.rb",
    "vendor/assets/images/aol_128.png",
    "vendor/assets/images/aol_256.png",
    "vendor/assets/images/aol_32.png",
    "vendor/assets/images/aol_64.png",
    "vendor/assets/images/basecamp_128.png",
    "vendor/assets/images/basecamp_256.png",
    "vendor/assets/images/basecamp_32.png",
    "vendor/assets/images/basecamp_64.png",
    "vendor/assets/images/campfire_128.png",
    "vendor/assets/images/campfire_256.png",
    "vendor/assets/images/campfire_32.png",
    "vendor/assets/images/campfire_64.png",
    "vendor/assets/images/facebook_128.png",
    "vendor/assets/images/facebook_256.png",
    "vendor/assets/images/facebook_32.png",
    "vendor/assets/images/facebook_64.png",
    "vendor/assets/images/github_128.png",
    "vendor/assets/images/github_256.png",
    "vendor/assets/images/github_32.png",
    "vendor/assets/images/github_64.png",
    "vendor/assets/images/google_128.png",
    "vendor/assets/images/google_256.png",
    "vendor/assets/images/google_32.png",
    "vendor/assets/images/google_64.png",
    "vendor/assets/images/linkedin_128.png",
    "vendor/assets/images/linkedin_256.png",
    "vendor/assets/images/linkedin_32.png",
    "vendor/assets/images/linkedin_64.png",
    "vendor/assets/images/myspace_128.png",
    "vendor/assets/images/myspace_256.png",
    "vendor/assets/images/myspace_32.png",
    "vendor/assets/images/myspace_64.png",
    "vendor/assets/images/openid_128.png",
    "vendor/assets/images/openid_256.png",
    "vendor/assets/images/openid_32.png",
    "vendor/assets/images/openid_64.png",
    "vendor/assets/images/presently_128.png",
    "vendor/assets/images/presently_256.png",
    "vendor/assets/images/presently_32.png",
    "vendor/assets/images/presently_64.png",
    "vendor/assets/images/twitter_128.png",
    "vendor/assets/images/twitter_256.png",
    "vendor/assets/images/twitter_32.png",
    "vendor/assets/images/twitter_64.png",
    "vendor/assets/images/yahoo_128.png",
    "vendor/assets/images/yahoo_256.png",
    "vendor/assets/images/yahoo_32.png",
    "vendor/assets/images/yahoo_64.png"
  ]
  s.homepage = %q{http://github.com/hulihanapplications/authbuttons-rails}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{A collection of authentication provider icons for Rails 3.1/Sprockets}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

